feign:
  client:
    config:
      default:
        logger-level: basic # 日志级别
  httpclient:
    enabled: true # 支持httpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数