server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # 路由标识
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 断言规则1：判断路径是否以 /user 开头，是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**

